wandb_version: 1

model:
  desc: null
  value: resnet50
epochs:
  desc: null
  value: 2
weights:
  desc: null
  value: DEFAULT
batch_size:
  desc: null
  value: 32
loss_func:
  desc: null
  value: CrossEntropyLoss
unfrozen_layers:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711576287.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.8
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
